"""内置工作流定义：备课、作业闭环、科研综述。"""

from app.services.workflow.base import WorkflowDefinition, WorkflowStep


WORKFLOWS: dict[str, WorkflowDefinition] = {
    "lesson_plan": WorkflowDefinition(
        id="lesson_plan",
        name="智能备课工作流",
        description="检索知识库 → 生成教案 → 按主题分支补充案例 → 保存并记录活动",
        steps=[
            WorkflowStep(id="retrieve", label="① 检索学科知识库", tool="rag.search",
                         params={"query": "{course} {topic}", "course": "{course}", "top_k": 4},
                         next="generate"),
            WorkflowStep(id="generate", label="② LLM 生成教案结构", tool="llm.generate",
                         params={"system": "你是高校计算机学科的智能备课助手，输出结构化教案 JSON。",
                                 "prompt": "课程：{course}\n章节：{chapter}\n教学主题：{topic}\n学生年级：{grade}\n教学目标：{objective}\n教学时长：{duration}\n学生水平：{level}\n班级学情参考：\n{class_analytics}\n知识库参考：\n{retrieve.text}\n请输出 JSON：objectives/knowledge_points/key_points/difficulties/flow/cases/exercises/homework"},
                         next="branch"),
            WorkflowStep(id="branch", label="③ 分支：主题是否含编程内容", type="branch",
                         condition="'编程' in {topic} or '算法' in {topic}",
                         next_yes="code_case", next_no="case_analysis"),
            WorkflowStep(id="code_case", label="④ 生成代码教学案例", tool="llm.generate",
                         params={"system": "你是高校计算机学科备课助手",
                                 "prompt": "为「{topic}」补充一个带代码的教学案例（含题目、思路、参考代码片段与易错点）。"},
                         next="save"),
            WorkflowStep(id="case_analysis", label="④ 生成概念辨析案例", tool="llm.generate",
                         params={"system": "你是高校计算机学科备课助手",
                                 "prompt": "为「{topic}」补充两个概念辨析/易错案例，帮助学生理解易混概念。"},
                         next="save"),
            WorkflowStep(id="save", label="⑤ 保存教案并记录活动", tool="lesson.save",
                         params={"course": "{course}", "chapter": "{chapter}", "topic": "{topic}",
                                 "grade": "{grade}", "parsed": "{generate.parsed}"},
                         next="done"),
        ],
    ),
    "assignment_loop": WorkflowDefinition(
        id="assignment_loop",
        name="作业闭环工作流",
        description="提交 → 按题型分支（编程评测 / AI 建议批改）→ 失败诊断 → 画像更新 → 教师审批",
        steps=[
            WorkflowStep(id="branch_type", label="① 分支：题目类型", type="branch",
                         condition="{qtype} == 'programming'",
                         next_yes="judge", next_no="ai_review"),
            WorkflowStep(id="judge", label="② 代码自动评测", tool="judge.run",
                         params={"source_code": "{source_code}", "language": "{language}",
                                 "test_cases": "{test_cases}"},
                         next="save_judge"),
            WorkflowStep(id="save_judge", label="③ 保存评测结果", tool="submission.save_judge",
                         params={"submission_id": "{submission_id}", "source_code": "{source_code}",
                                 "language": "{language}"},
                         next="branch_verdict"),
            WorkflowStep(id="branch_verdict", label="③ 分支：评测是否通过", type="branch",
                         condition="{judge.verdict} == 'accepted'",
                         next_yes="profile_update", next_no="diagnose"),
            WorkflowStep(id="diagnose", label="⑤ AI 错误诊断", tool="diagnose.code",
                         params={"question_title": "{question_title}",
                                 "question_description": "{question_description}",
                                 "source_code": "{source_code}", "language": "{language}",
                                 "judge_report": "{judge.judge_report}",
                                 "error_message": "{judge.error_message}", "mode": "hint"},
                         next="profile_update"),
            WorkflowStep(id="ai_review", label="② AI 建议批改", tool="grading.ai_review",
                         params={"submission_id": "{submission_id}"},
                         next="activity_sub"),
            WorkflowStep(id="activity_sub", label="③ 记录提交活动", tool="activity.log",
                         params={"kind": "subjective_submit",
                                 "title": "提交简答题《{question_title}》，等待教师批改",
                                 "detail": {"submission_id": "{submission_id}"}},
                         next="approve"),
            WorkflowStep(id="profile_update", label="⑥ 更新学习画像", tool="analytics.update_profile",
                         params={"submission_id": "{submission_id}",
                                 "correct": "{judge.verdict}"},
                         next="activity"),
            WorkflowStep(id="activity", label="⑦ 记录学习活动", tool="activity.log",
                         params={"kind": "code_submit",
                                 "title": "提交《{question_title}》：{judge.passed_tests}/{judge.total_tests} 通过",
                                 "detail": {"submission_id": "{submission_id}"}},
                         next="done"),
            WorkflowStep(id="approve", label="④ 等待教师确认成绩", type="approval",
                         approval_role="teacher", next="done"),
        ],
    ),
    "research_review": WorkflowDefinition(
        id="research_review",
        name="科研综述工作流",
        description="检索论文 → 分支（有无论文）→ 逐篇精读聚合 → 知识库参考 → LLM 生成综述",
        steps=[
            WorkflowStep(id="papers", label="① 检索论文库", tool="papers.search",
                         params={"topic": "{topic}", "limit": 8}, next="branch"),
            WorkflowStep(id="branch", label="② 分支：是否检索到论文", type="branch",
                         condition="{papers.count} > 0",
                         next_yes="summary", next_no="llm_only"),
            WorkflowStep(id="summary", label="③ 逐篇 AI 精读并聚合", tool="papers.summary",
                         params={"papers": "{papers.papers}", "topic": "{topic}"},
                         next="knowledge"),
            WorkflowStep(id="llm_only", label="③ 仅凭模型知识生成综述", tool="research.generate_review",
                         params={"topic": "{topic}"},
                         next="done"),
            WorkflowStep(id="knowledge", label="④ 检索知识库补充背景", tool="rag.search",
                         params={"query": "{topic}", "top_k": 3}, next="generate_review"),
            WorkflowStep(id="generate_review", label="⑤ LLM 生成综述", tool="research.generate_review",
                         params={"topic": "{topic}"},
                         next="done"),
        ],
    ),
    "preview": WorkflowDefinition(
        id="preview",
        name="课前预习工作流",
        description="检索官方资料 → 预习 Agent 生成目标/预备知识/概念/预习题 → 记录学习行为",
        steps=[
            WorkflowStep(id="retrieve", label="① 检索课程官方资料", tool="rag.search",
                         params={"query": "{course} {chapter}", "course_id": "{course_id}", "source_levels": ["S"], "top_k": 4},
                         next="agent"),
            WorkflowStep(id="agent", label="② 预习 Agent 生成预习包", tool="agent.run",
                         params={"agent": "preview", "course_id": "{course_id}", "chapter_id": "{chapter_id}"},
                         next="record"),
            WorkflowStep(id="record", label="③ 记录预习行为", tool="learning.record",
                         params={"action": "preview", "course_id": "{course_id}", "chapter_id": "{chapter_id}",
                                 "detail": {"workflow": "preview"}},
                         next="done"),
        ],
    ),
    "lecture": WorkflowDefinition(
        id="lecture",
        name="AI 课程讲堂工作流",
        description="检索官方/共享资料 → 讲堂 Agent 按深度生成结构化课程 → 记录学习行为",
        steps=[
            WorkflowStep(id="retrieve", label="① 检索课程资料（S/A）", tool="rag.search",
                         params={"query": "{course} {chapter}", "course_id": "{course_id}", "source_levels": ["S", "A"], "top_k": 5},
                         next="branch"),
            WorkflowStep(id="branch", label="② 分支：讲解深度", type="branch",
                         condition="{depth} == 'deep'",
                         next_yes="agent", next_no="agent_standard"),
            WorkflowStep(id="agent", label="③ 讲堂 Agent（深度讲解）", tool="agent.run",
                         params={"agent": "lecture", "chapter_id": "{chapter_id}", "depth": "{depth}"},
                         next="record"),
            WorkflowStep(id="agent_standard", label="③ 讲堂 Agent（快速/标准）", tool="agent.run",
                         params={"agent": "lecture", "chapter_id": "{chapter_id}", "depth": "{depth}"},
                         next="record"),
            WorkflowStep(id="record", label="④ 记录讲堂学习行为", tool="learning.record",
                         params={"action": "lecture", "course_id": "{course_id}", "chapter_id": "{chapter_id}",
                                 "detail": {"workflow": "lecture", "depth": "{depth}"}},
                         next="done"),
        ],
    ),
    "review": WorkflowDefinition(
        id="review",
        name="课后复习工作流",
        description="检索资料 + 学习画像 → 复习 Agent 生成总结/薄弱点计划/强化练习 → 记录",
        steps=[
            WorkflowStep(id="retrieve", label="① 检索课程资料", tool="rag.search",
                         params={"query": "{course} {chapter} 复习", "course_id": "{course_id}", "source_levels": ["S", "A"], "top_k": 4},
                         next="agent"),
            WorkflowStep(id="agent", label="② 复习 Agent 生成复习包", tool="agent.run",
                         params={"agent": "review", "chapter_id": "{chapter_id}", "course_id": "{course_id}"},
                         next="record"),
            WorkflowStep(id="record", label="③ 记录复习行为", tool="learning.record",
                         params={"action": "review", "course_id": "{course_id}", "chapter_id": "{chapter_id}",
                                 "detail": {"workflow": "review"}},
                         next="done"),
        ],
    ),
    "exam_build": WorkflowDefinition(
        id="exam_build",
        name="考前模拟-出卷工作流",
        description="检索资料 → 模拟考试 Agent 按类型生成试卷（代码题接入 Judge）",
        steps=[
            WorkflowStep(id="retrieve", label="① 检索课程资料", tool="rag.search",
                         params={"query": "{course} 测验", "course_id": "{course_id}", "source_levels": ["S", "A"], "top_k": 4},
                         next="agent"),
            WorkflowStep(id="agent", label="② 模拟考试 Agent 生成试卷", tool="agent.run",
                         params={"agent": "exam", "task": "build", "course_id": "{course_id}",
                                 "chapter_id": "{chapter_id}", "quiz_type": "{quiz_type}", "scope_kp_ids": "{scope_kp_ids}"},
                         next="done"),
        ],
    ),
    "exam_grade": WorkflowDefinition(
        id="exam_grade",
        name="考前模拟-评分工作流",
        description="评分（客观题自动 + 代码题接入 Judge）→ 更新画像 → 生成复习建议",
        steps=[
            WorkflowStep(id="agent", label="① 模拟考试 Agent 评分", tool="agent.run",
                         params={"agent": "exam", "task": "grade", "quiz_id": "{quiz_id}", "answers": "{answers}"},
                         next="record"),
            WorkflowStep(id="record", label="② 记录模拟考试行为", tool="learning.record",
                         params={"action": "exam", "course_id": "{course_id}", "chapter_id": "{chapter_id}",
                                 "detail": {"workflow": "exam_grade", "quiz_id": "{quiz_id}"}},
                         next="done"),
        ],
    ),
    "diagnose": WorkflowDefinition(
        id="diagnose",
        name="教学诊断工作流",
        description="统计班级学情 → 诊断 Agent 生成问题/证据/建议 → 可“采用建议”进入教学设计",
        steps=[
            WorkflowStep(id="analytics", label="① 汇总班级学情", tool="analytics.class",
                         params={"course_id": "{course_id}"}, next="agent"),
            WorkflowStep(id="agent", label="② 诊断 Agent 生成诊断与建议", tool="agent.run",
                         params={"agent": "diagnose", "course_id": "{course_id}"},
                         next="done"),
        ],
    ),
    "tutor": WorkflowDefinition(
        id="tutor",
        name="课程答疑工作流",
        description="导师 Agent 按资料范围检索课程知识空间并回答（命中则引用，未命中明确扩展知识）→ 保存对话历史",
        steps=[
            WorkflowStep(id="agent", label="① 学科导师 Agent 回答（RAG 命中/扩展知识）", tool="agent.run",
                         params={"agent": "learning", "message": "{message}", "mode": "{mode}",
                                 "history": "{history}", "course_id": "{course_id}", "chapter_id": "{chapter_id}",
                                 "scope": "{scope}", "image_base64": "{image_base64}"},
                         next="done"),
        ],
    ),
}


def get_workflow_definition(definition_id: str) -> WorkflowDefinition | None:
    return WORKFLOWS.get(definition_id)
